
func() begin
  try
    a:=3;
    a:=4;
  onexception |ex.test| do
    c:=4;
  onexception |ex.test| do
    c:=5;
end
